name: CI
on:
  push:
    paths-ignore:
      - 'public/**'
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      #- name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        #run: git submodule update --init --recursive
                                                              
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"
                                                              
      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --cleanDestinationDir 
                                                              
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY  }}
          #external_repository: <username>/<username>.github.io
          publish_dir: ./public
          destination_dir: ./public
          #   keep_files: true
          user_name: edyatl
          user_email: edyatl@yandex.ru
          publish_branch: master
          commit_message: "Deploy: ${{ github.event.head_commit.message  }} [skip netlify]"
          #   cname: example.com
